### ISSUE TITLE
Bug with delete event

### ISSUE THREAD

**Issue by majordoobie** [majordoobie/HogRider#7]
```py
ERROR | HogRider.BotClient
Traceback (most recent call last):
File "/opt/venv/lib/python3.11/site-packages/disnake/client.py", line 703, in _run_event
await coro(*args, **kwargs)
File "/opt/code/packages/cogs/event_driver.py", line 241, in on_raw_message_delete
user = self.bot.get_user(message.user_id)
^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'user_id'
Version: 2.0.2
```

Figure out what is going on here

**Comment by majordoobie** [comment]
Fixed with update 2.0.7
